// <auto-generated />
using System;
using administracion.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace administracion.Migrations
{
    [DbContext(typeof(AdminDBContex))]
    partial class AdminDBContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Administracion.Persistence.Entities.Asegurado", b =>
                {
                    b.Property<Guid>("aseguradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("aseguradoId");

                    b.ToTable("Asegurados");

                    b.HasData(
                        new
                        {
                            aseguradoId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530821c03f"),
                            apellido = "Banderas Lopez",
                            nombre = "Manuel Diego"
                        },
                        new
                        {
                            aseguradoId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530821c03b"),
                            apellido = "Ramirez Gimenez",
                            nombre = "Luis Jose"
                        });
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Incidente", b =>
                {
                    b.Property<Guid>("incidenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("polizaId")
                        .HasColumnType("uuid");

                    b.HasKey("incidenteId");

                    b.HasIndex("polizaId");

                    b.ToTable("incidentes");

                    b.HasData(
                        new
                        {
                            incidenteId = new Guid("75045fa2-7e8d-48d4-a02f-6ea13e599984"),
                            estado = 0,
                            polizaId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530823c05b")
                        });
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Poliza", b =>
                {
                    b.Property<Guid>("polizaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaVencimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("tipoPoliza")
                        .HasColumnType("integer");

                    b.Property<Guid>("vehiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("polizaId");

                    b.HasIndex("vehiculoId");

                    b.ToTable("Polizas");

                    b.HasData(
                        new
                        {
                            polizaId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530823c05b"),
                            fechaInicio = new DateTime(2022, 6, 15, 21, 0, 59, 388, DateTimeKind.Local).AddTicks(6774),
                            fechaVencimiento = new DateTime(2022, 6, 15, 21, 0, 59, 388, DateTimeKind.Local).AddTicks(6775),
                            tipoPoliza = 0,
                            vehiculoId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530821c04b")
                        });
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("vehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("anioModelo")
                        .HasColumnType("integer");

                    b.Property<Guid>("aseguradoId")
                        .HasColumnType("uuid");

                    b.Property<int>("color")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaCompra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("marca")
                        .HasColumnType("integer");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("vehiculoId");

                    b.HasIndex("aseguradoId");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            vehiculoId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530821c04b"),
                            anioModelo = 2004,
                            aseguradoId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530821c03b"),
                            color = 1,
                            fechaCompra = new DateTime(2022, 6, 15, 21, 0, 59, 388, DateTimeKind.Local).AddTicks(6756),
                            marca = 0,
                            placa = "AB320AM"
                        },
                        new
                        {
                            vehiculoId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530821c05b"),
                            anioModelo = 2006,
                            aseguradoId = new Guid("0c5c3262-d5ef-46c7-bc0e-97530821c03f"),
                            color = 6,
                            fechaCompra = new DateTime(2022, 6, 15, 21, 0, 59, 388, DateTimeKind.Local).AddTicks(6770),
                            marca = 0,
                            placa = "AB322AM"
                        });
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Incidente", b =>
                {
                    b.HasOne("Administracion.Persistence.Entities.Poliza", "poliza")
                        .WithMany("incidente")
                        .HasForeignKey("polizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("poliza");
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Poliza", b =>
                {
                    b.HasOne("Administracion.Persistence.Entities.Vehiculo", "vehiculo")
                        .WithMany("polizas")
                        .HasForeignKey("vehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehiculo");
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Vehiculo", b =>
                {
                    b.HasOne("Administracion.Persistence.Entities.Asegurado", "asegurado")
                        .WithMany("vehiculos")
                        .HasForeignKey("aseguradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asegurado");
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Asegurado", b =>
                {
                    b.Navigation("vehiculos");
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Poliza", b =>
                {
                    b.Navigation("incidente");
                });

            modelBuilder.Entity("Administracion.Persistence.Entities.Vehiculo", b =>
                {
                    b.Navigation("polizas");
                });
#pragma warning restore 612, 618
        }
    }
}
